### ISSUE TITLE
Module 1: Personas (users with roles)

### ISSUE THREAD

**Issue by dober-man** [f5devcentral/f5-big-iq-lab#11]
"David and Marco will have full access to BIG-IQ. He knows a lot about F5 products (BIG-IQ/BIG-IP). He will provide the access to David, Larry and Paula. He will also manage the Service Scaling Group (SSG) and application templates."

Who knows a lot about f5? David or Marco? Why would Marco provide access for David if he is an admin too. Who is providing access for Paul and Olivia? 

Suggesting this be rewritten to: 

"David and Marco will have full access to BIG-IQ. David knows a lot about F5 products (BIG-IQ/BIG-IP). He will provide the access to Larry, Olivia, Paul and Paula. He will also manage the Service Scaling Group (SSG) and application templates."

**Comment by rjouhann** [comment]
Thanks for the feedback. I will fix the description in the next push.
