### ISSUE TITLE
Update 6.0 Content to 6.1

### ISSUE THREAD

**Issue by dober-man** [f5devcentral/f5-big-iq-lab#12]
![image](https://user-images.githubusercontent.com/6983503/52014424-7d33ce00-24ad-11e9-9a40-c0763ea6f1e6.png)

Lab 2.2 says: "Edit the Policy f5-asm-policy1, switch to Manual Learning Mode and Make available in Application Templates, click Save."

Per the screenshot the policy is already set to manual, can not be changed and trust xff is set by default. Same thing if I'm logged in as admin. 

Requesting update to: 

* Include new screenshot

* "Edit the Policy f5-asm-policy1, notice the leaning mode is set to manual and Trust XFF is enabled.  
Above Learning Mode select "Make available in Application Templates", click Save."

It seems there is a mix of 6.0 and 6.1 content in this lab guide. Moving forward are we going to clean up the older instructions and screenshots with 6.1 and beyond. As a first time student, the note and the warning are confusing at the bottom of lab 2.1. 

I am happy to document any cases where this needs to be updated as I go through the labs. Would you prefer to work these as issues or clone and pull?

**Comment by rjouhann** [comment]
Yes the lab guide is aimed to support both 6.0 and 6.1 blueprints.
I will make the updates.
Please email me directly for future comments (if you work from F5 Networks).
Roman Jouhannet
