### ISSUE TITLE
Re-Discovery SEA 14.0 installation

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-iq-lab#2]
Issue with default "No TLSv1.3" option in BIG-IQ until its discovered from a BIG-IP with this option (a 14.0 installation).

Issue described: 

TLSv1.3 is not an option in BIG-IQ 6.0.1, this feature is required for pushing applications to a 14.0 BIG-IP since the default on the SEA image is Cipher List this breaks all kinds of things. Its possible the resolution for this is a re-discovery of the 14.0 image for SEA, this would bring in the No TLSv1.3 option and should allow you to reference it correctly, problem here though is what if I have a 12/13/14 editions managed, no sure what will happen if we do this route them push the -secure profile to a 12.X BIG-IP. This issue currently breaks the first application in the lab

![unknown](https://user-images.githubusercontent.com/20847865/45338541-80501100-b542-11e8-8d43-3d12aae40f63.png)

@vbojko @JeffGiroux

**Comment by rjouhann** [comment]
Re-import the SEA BIG-IP added the No TLSv1.3.
This will be fixed in version 9 of the blueprint.

![image](https://user-images.githubusercontent.com/25542366/45383734-e9766980-b5c0-11e8-8429-a35400ddfeeb.png)
