### ISSUE TITLE
AWS_US_EAST Variables Hardcoded

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-iq-lab#5]
Variables "AWS_US_EAST_1A" and "AWS_US_EAST_1B" are hardcoded values for the 08 script, these variables are confusing since we could potentially be deploying a solution in WEST, or EU.

Fix would be to call out different variable names, or more notes on the config.yml file

@bwesterf5

**Comment by rjouhann** [comment]
Renamed the variables to AWS_AZ_1A and AWS_AZ_1B
