### ISSUE TITLE
Typo cause error 400

### ISSUE THREAD

**Issue by SalinaYu** [f5devcentral/f5-big-iq-lab#55]
For https://raw.githubusercontent.com/f5devcentral/f5-big-iq-lab/develop/docs/class1/module2/lab2.rst

In Task5b section:
The code-block will pass the validation, yet when you actually sent it to BIG-IQ via REST, the check deployment task will return with the error as following:

..."results": [ { "message": "for action 'patch', a patchBody must be included - refer to AS3 docs for details", "code": 400 } ] ...

When you change "patchbody" to "patchBody" in the code-block and then sent it to BIG-IQ without producing any error.

**Comment by rjouhann** [comment]
Thanks @SalinaYu ! I have corrected the typo which should be online in few minutes.
