### ISSUE TITLE
RFE: Central Policy Management Lab

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/f5-big-iq-lab#57]
Please consider writing a lab for CPM  (WAF). 
https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class8/module1/lab3.html

Sample scenario: 

- Build policy
- Deploy policy
- WAF Dashboard shows alert
- Modify policy 
- Deploy policy

**Comment by rjouhann** [comment]
We have those 2 lab already around AS3 and WAF:

[Class1/Module3/Lab 3.6: Deploy a WAF with BIG-IQ and AS3 using an ASM policy on BIG-IP](https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class1/module3/lab6.html)
[Class1/Module3/Lab 3.7: Deploy a WAF with BIG-IQ and AS3 using an ASM policy on GitHub](https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class1/module3/lab7.html)

We are going to start working on Class8/Module1/Lab3:

**Lab 1.3: WAF Policy Management via GitLab CI/CD pipeline with default WAF template and AS3:**
- Build policy and logging profile on BIG-IQ using the BIG-IQ UI
- Deploy to BIG-IP with API through Gitlab and Ansible
- Deploy AS3 referencing existing WAF policy and logging profile with API through Gitlab and Ansible
- Update policy through BIG-IQ, deploy policy update using the BIG-IQ UI

**We are also thinking about building the following lab:**
(Previous workflow + source of truth xml policy on Git repo)
- @ starting point Policy template is stored in git repo            
- Import policy template to BIG-IQ using API with API through Gitlab and Ansible
- Build policy based on template on BIG-IQ using API with API through Gitlab and Ansible
- Deploy to BIG-IP (inactive vs + pinning as appropriate)
- Deploy AS3 referencing existing WAF policy with API through Gitlab and Ansible
- Update policy through BIG-IQ, deploy policy update using the BIG-IQ UI

**Comment by rjouhann** [comment]
I have published this new lab:

Lab 1.3: WAF Policy Management via GitLab CI/CD pipeline with default WAF template and AS3
https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class8/module1/lab3.html
