### ISSUE TITLE
Deploy VS config on multiple BIG-IPs at once with BIG-IQ CM 

### ISSUE THREAD

**Issue by gwolfis** [f5devcentral/f5-big-iq-lab#73]
When configuring a new VS on BIG-IQ to be deployed on multiple BIG-IPs at once.

I have used the BIG-IQ UDF lab to reproduce
1. You create a VS at the BIG-IQ > Configuration > Local Traffic > Virtual Servers tab.
2. Once saved you will use the Deployment > Evaluate & Deploy > Local Traffic & Network tab to first evaluate and then deploy the new VS.
For this I have selected a BIG-IP Cluster (both units) and a single BIG-IP to mimic multiple BIG-IPs who should receive the same VS config. (see attached image)
3. Both Evaluation and Deployment work, but at the deployment phase you will notice an error. (See attached image)

Result:
The VS will get configured on one BIG-IP but not on both selected BIG-IPs (Cluster + single unit). I have checked the actual BIG-IP config and the cluster got the config and the single unit not.

Another observation is the fact that you already define a device at the VS config section, why? I would expect this not here but just at the Deployment section, this feels kind of redundant and confuses customers when they want to deploy the same config to multiple different BIG-IPs or clusters.

![ScreenHunter_1467 Jan  12 20 59](https://user-images.githubusercontent.com/20405085/104443831-373b7c00-5597-11eb-8767-84f571a6452a.jpg)
![ScreenHunter_1468 Jan  12 21 31](https://user-images.githubusercontent.com/20405085/104443841-3acf0300-5597-11eb-9430-690943cb486e.jpg)

**Comment by rjouhann** [comment]
Hello Gert,

Did you do a full device re-discovery beforehand?

I did the following test and it worked for me.

1. Re-Import and Re-Discover the devices to make sure the config between BIG-IQ and BIG-IP are in sync.

![image](https://user-images.githubusercontent.com/25542366/104617542-6954e880-5640-11eb-89ea-627690082dea.png)

2. Create VIP 1 on Boston Cluster
![image](https://user-images.githubusercontent.com/25542366/104617185-fd728000-563f-11eb-8056-1d233c046a5b.png)

3. Create VIP 2 on Standalone Seattle
![image](https://user-images.githubusercontent.com/25542366/104617273-18dd8b00-5640-11eb-87aa-5e79d9082832.png)

4. Now the VIPs are on BIG-IQ in the working config.
![image](https://user-images.githubusercontent.com/25542366/104617306-24c94d00-5640-11eb-8f54-2be230b40451.png)

5. There are 2 ways to deploy those 2 VIPs:

5.1. from the config tab, select the VIPs, in the menu, select more, then deploy => this will do a partial deploy
5.1. from the deployment tab under LTM, create an Evaluation & Deploy => here you can choose the full or partial deployment

6. In your example, you did a full deployment. Doing the evaluation first.

![image](https://user-images.githubusercontent.com/25542366/104617924-e7b18a80-5640-11eb-800c-e3808ac4d6b0.png)

![image](https://user-images.githubusercontent.com/25542366/104619300-8db1c480-5642-11eb-9ef3-8d9293dac41a.png)

7. Then, deploy the config to both devices.

![image](https://user-images.githubusercontent.com/25542366/104619623-f1d48880-5642-11eb-954a-ead885ea85a5.png)

![image](https://user-images.githubusercontent.com/25542366/104619696-0749b280-5643-11eb-9593-e5a9c2c01158.png)

8. After the deployment is completed, the VIPs are in the current config on BIG-IQ and on the BIG-IPs.

![image](https://user-images.githubusercontent.com/25542366/104620492-e6359180-5643-11eb-9172-c2aa9aedd6ac.png)

Thanks & Regards,
Roman
