### ISSUE TITLE
All Devices Licenses Expiring

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-iq-lab#9]
Device level licenses are expiring if you are not connected to the VPN for recycle option to reconcile. 

![internal pd license](https://user-images.githubusercontent.com/20847865/46827386-54949680-cd4d-11e8-800a-99a9a1ae54d4.png)

**Comment by jmcalalang** [comment]
@aknot242 is running a class next week

**Comment by rjouhann** [comment]
I am going to publish a new blueprint today in UDF with few updates including the reactivation of those licenses (look for version 12). I need to work on a script to re-activate those licenses (TBD).
For Ravello, people have to re-fresh the licenses (BIG-IP/BIG-IQ/license pool) themselves, then save the blueprint to a new blueprint to use for their classes.

**Comment by jmcalalang** [comment]
Can we get a list of the licenses, needed for each instance, the pools aren't super obvious its VEP7 and addon amount etc. Are you going to update the BP in Ravello as well for Rev 12? or is that on a different interval? 

Does this WAG work?

BIGIQ CM: Max IQ
  byol-pool:  VEP7, App Services Bundle, 1G, 48 Instances (total with addons)
  byol-pool-access:  VEP2, Better, 1G, 25 Instances
  byol-pool-perAppVE: Advanced WAF, 200M Per App VE, 20 Instances
  byol-pool-utility: BIG-IP, MSP/CLPV2, LOADV1
BIGIQ DCD: Log IQ
BOS-vBIGIP01: Best 1G
BOS-vBIGIP02: Best 1G
SEA-vBIGIP01: Best 1G
TLV-vBIGIP01: Best 1G

**Comment by rjouhann** [comment]
yes, the above licenses works. version 12 is published in UDF.

**Comment by jmcalalang** [comment]
im missing this one: byol-pool-perAppVE do you remember which one you used? it looks like pool of awaf, also so we arent going to see your updates from udf 12 into ravello, is it things we need or was it just for the reactivate?

**Comment by rjouhann** [comment]
This is the perAppVE WAF license, same as the one we sell to our customers. The updates made in UDF aren't going to be replicated in Ravello. Also note the licenses are dev license and will need to be re-activated manually via the dossier or new EVAL licenses can be used.

**Comment by jmcalalang** [comment]
yeah I'm targeting eval licenses since that way the process is slightly quicker, we have to replace them all anyway you cant reactivate pool licenses with new keys like a bigip. 

the name is stupid: **F5-BIG-WAF-PVE200MV16-LIC** doesnt say anything to do with AWAF :(. updated the piece above.

is there a good place to note this? the issue will eventually be closed now that the responsibility is on the instructor for classes
