### ISSUE TITLE
Module 3: HTTP Traffic Capture Analytics in BIG-IQ

### ISSUE THREAD

**Issue by dojsbr** [f5devcentral/f5-big-iq-lab#90]
Hi,
 i'd like to see this lab. Please Share

**Comment by rjouhann** [comment]
There is, unfortunately, nobody available to work on this lab at the moment.

Please find more information in the BIG-IQ Product documentation:

https://techdocs.f5.com/en-us/bigiq-8-0-0/monitoring-managing-applications-using-big-iq/monitoring-application-services/enable-traffic-capturing.html#enable-traffic-capturing
