### ISSUE TITLE
Template WAF External URL

### ISSUE THREAD

**Issue by dojsbr** [f5devcentral/f5-big-iq-lab#91]
I got the same error when i used AS3 on lab-guide and now on the lab
https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class8/module1/lab5.html

![Screenshot_1](https://user-images.githubusercontent.com/41028877/114290653-8c344480-9a57-11eb-8ac2-ba648b0798b1.png)

status: 422: /declare failed with status of 422, Failed to send declaration: java.lang.NumberFormatException: For input string: "ECONNREFUSED"

I tried some changes of value without success. Now i'm using v8

**Comment by rjouhann** [comment]
Please file a support request through F5 support, or contact your sales representative to do so on your behalf.

Make sure to provide the name of the template (if part of the [default ones](https://github.com/f5devcentral/f5-big-iq)) or export of the template using a custom one. Also, share the input values you are entering in the template and AS3 declaration when clicking on "View API sample" at app service deployment.

Thanks & Regards,
Roman
