### ISSUE TITLE
mon-https does not show up when trying to add it to the pool

### ISSUE THREAD

**Issue by gwolfis** [f5devcentral/f5-big-iq-lab#92]
https://clouddocs.f5.com/training/community/big-iq-cloud-edition/html/class5/module4/lab1.html

Creating the https monitor is not a problem, that works.

But adding the monitor in the next step to pool app2pool, you can't select the just created monitor from the dropdown menu.

**Comment by rjouhann** [comment]
Hello,
There is a missing step, after creating the monitor, you need to pin it to the device before using it.
I will update the lab guide.
Thanks
