### ISSUE TITLE
Target hardcoded in the Jinja templates for AS3+AWX was a little confusing

### ISSUE THREAD

**Issue by vsnine** [f5devcentral/f5-big-iq-lab#94]
Hi all,

Appreciate the labs so far, they have been helpful in learning more about AS3 and Ansible. I wanted to note one issue (during A&O Toolchain 214) that caught me up for a little bit was that the target BIG-IP address was hardcoded into the template j2 file instead of possibly being exposed in the Ansible AWX survey. I think it could have been helpful to let that be configurable with a default value in the survey, and note the capability in the lab guide.

Related to http_app.j2 and delete_app.j2 in lab/f5-ansible-bigiq-as3-demo/tower/j2

Thanks.

**Comment by rjouhann** [comment]
Hello @vsnine 
Those labs are examples, you are welcome to fork the repo and make it your own or submit a pull request with your suggestions.
Thanks!
